// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AkeaAnimatedBattleSystem","status":false,"description":"Akea Animated Battle System 2","parameters":{"Frame Configuration":"","Actor Configuration":"","Actor Poses":"","Enemy Configuration":"","Enemy Poses":"","Poses":"","Actions":"","Script":"","entryActors":"","entryEnemies":"","returnAction":"","idleAction":"","stepForward":"","retreat":"","damage":"","evade":""}},
{"name":"SRD_SummonCore","status":false,"description":"Allows developers to create skills that summon Actors into the player's party using various parameters.","parameters":{"Battlelog Message":"%1 has been summoned!","Max Summons":"4","Restrict Per Skill":"true","Restrict Per Position":"true","== Defaults ==":"","Default Actor ID":"1","Default Level":"1","Default Animation":"51","Default Exit Ani.":"51","Default Turns":"-1","Default X Pos":"master._homeX - 120","Default Y Pos":"master._homeY"}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}}
];
